package com.posullivan.springmvc.dto;

import java.util.List;

import javax.validation.constraints.Max;
import javax.validation.constraints.Min;
import javax.validation.constraints.NotNull;
import javax.validation.constraints.Size;

public class Vehicle {
	
	// The id will be generated by the system
	private Long id;

	@NotNull
	@Size(min = 2, max = 25)
	private String make;

	@NotNull
	@Size(min = 2, max = 50)
	private String model;

	@NotNull
	// @Size(min = 4, max = 4) - Not applicable to integers
	@Min(1900)
	@Max(2099)
	private Integer year;

	// The transaction will contain the real price
	@NotNull
	// @Min(1000) - Using range validator
	// @Max(99999) - Using range validator
	@org.hibernate.validator.constraints.Range(min=1000, max=99999)
	private Integer guidePrice;
	
	private List<Transaction> transactions;
	
	public Vehicle() {
	}

	public Vehicle(String make, String model, Integer year, Integer guidePrice, List<Transaction> transactions) {
		this.make = make;
		this.model = model;
		this.year = year;
		this.guidePrice = guidePrice;
		this.transactions = transactions;
	}

	public Long getId() {
		return id;
	}

	public void setId(Long id) {
		this.id = id;
	}

	public String getMake() {
		return make;
	}

	public void setMake(String make) {
		this.make = make;
	}

	public String getModel() {
		return model;
	}

	public void setModel(String model) {
		this.model = model;
	}

	public Integer getYear() {
		return year;
	}

	public void setYear(Integer year) {
		this.year = year;
	}

	public Integer getGuidePrice() {
		return guidePrice;
	}

	public void setGuidePrice(Integer guidePrice) {
		this.guidePrice = guidePrice;
	}

	public List<Transaction> getTransactions() {
		return transactions;
	}

	public void setTransactions(List<Transaction> transactions) {
		this.transactions = transactions;
	}
	
}
